# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'TestTaskMosgorpass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'YandexMapsMobile', '4.1.0-full'
  pod 'UltraDrawerView', '0.7.1'

  # Pods for TestTaskMosgorpass

  target 'TestTaskMosgorpassTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Quick', '5.0.1'
    	pod 'Nimble', '10.0.0'
  end

  target 'TestTaskMosgorpassUITests' do
    # Pods for testing
  end

end
